/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMatchDotjsonRouteImport } from './routes/api/match[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchDotjsonRoute = ApiMatchDotjsonRouteImport.update({
  id: '/api/match.json',
  path: '/api/match.json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/match.json': typeof ApiMatchDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/match.json': typeof ApiMatchDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/match.json': typeof ApiMatchDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/match.json'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/match.json'
  id: '__root__' | '/' | '/api/match.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMatchDotjsonRoute: typeof ApiMatchDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match.json': {
      id: '/api/match.json'
      path: '/api/match.json'
      fullPath: '/api/match.json'
      preLoaderRoute: typeof ApiMatchDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMatchDotjsonRoute: ApiMatchDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
